package io.github.jiangjil.ai4s.runtime.domain;

/** MVP Runtime 产生的追加式事件类型。 */
public enum TaskEventType {
    TASK_CREATED,
    TASK_STARTED,
    TASK_PAUSED,
    TASK_RESUMED,
    STEP_READY,
    STEP_CLAIMED,
    STEP_LEASE_RENEWED,
    STEP_RECEIPT_AMENDED,
    STEP_STARTED,
    JOB_SUBMISSION_REQUESTED,
    JOB_SUBMITTED,
    JOB_RUNNING,
    CHECKPOINT_SAVED,
    JOB_COMPLETED,
    JOB_LOST,
    STEP_SUCCEEDED,
    STEP_RETRY_SCHEDULED,
    STEP_FAILED,
    TASK_COMPLETED
}
